import os

# Función para escribir el archivo scanner.py.
def write_scanner(filename, regex, yalex_code):

    # Líneas de código fijas del archivo.
    lines = [
        "# This file was generated by the Yalex compiler.",
        "# Do not modify this file.",
        "",
        "import sys",
        "import os",
        "from utils.direct_construction import direct_construction",
        "from utils.simulate_yalex_file import simulate_yalex_file",
        "from utils.path_cleaner import replace_slash_with_backslash",
        "",
        "dfa = direct_construction(",
        f"    {regex},",
        f"    {yalex_code}",
        ")",
        "",
        "raw_file = input(\"Enter the path of the yal testing file: \")",
        "test_file = replace_slash_with_backslash(raw_file)",
        "file_name = os.path.basename(test_file).split('.')[0]",
        "output_file = f\"./out/{file_name}_tokens.txt\"",
        "output_type = \"analysis\"",
        "",
        "def return_token(found_token):",
    ]

    # Listas con el código y los tokens del archivo yalex.
    code_to_write = [entry[0] for entry in yalex_code]
    tokens_to_return = [entry[1] for entry in yalex_code]

    # Separador entre la función y la definición de los tokens.
    lines.append("")

    # Definición de los tokens.
    for token in tokens_to_return:
        lines.append(f"    {token} = \"{token}\"")

    # Separador entre los tokens y el código a retornar.
    lines.append("")

    # Escritura del código a retornar.
    for yalex_code, token in zip(code_to_write, tokens_to_return):
        lines.append(f"    if (found_token == {token}):")
        lines.append(f"        {yalex_code}")

    # Llamada final a la simulación del archivo.
    lines.append("")
    lines.append("simulate_yalex_file(test_file, output_file, dfa, output_type, return_token)")

    # Escritura del archivo scanner.py.
    with open(filename, "w+") as file:
        for line in lines:
            file.write(line + "\n")

    # Mensaje de éxito.
    print(f"\nScanner written successfully.\n")
