# This file was generated by the Yalex compiler.
# Do not modify this file.

import os
from algorithms.direct_construction import dfa_direct_construction
from yal_processing.simulate_yalex_file import simulate_yalex_file
from utils.path_cleaner import replace_slash_with_backslash

dfa = dfa_direct_construction(
    ['32', '9', '|', '10', '|', '+', '#0', '.', '65', '66', '|', '67', '|', '68', '|', '69', '|', '70', '|', '71', '|', '72', '|', '73', '|', '74', '|', '75', '|', '76', '|', '77', '|', '78', '|', '79', '|', '80', '|', '81', '|', '82', '|', '83', '|', '84', '|', '85', '|', '86', '|', '87', '|', '88', '|', '89', '|', '90', '|', '97', '|', '98', '|', '99', '|', '100', '|', '101', '|', '102', '|', '103', '|', '104', '|', '105', '|', '106', '|', '107', '|', '108', '|', '109', '|', '110', '|', '111', '|', '112', '|', '113', '|', '114', '|', '115', '|', '116', '|', '117', '|', '118', '|', '119', '|', '120', '|', '121', '|', '122', '|', '65', '66', '|', '67', '|', '68', '|', '69', '|', '70', '|', '71', '|', '72', '|', '73', '|', '74', '|', '75', '|', '76', '|', '77', '|', '78', '|', '79', '|', '80', '|', '81', '|', '82', '|', '83', '|', '84', '|', '85', '|', '86', '|', '87', '|', '88', '|', '89', '|', '90', '|', '97', '|', '98', '|', '99', '|', '100', '|', '101', '|', '102', '|', '103', '|', '104', '|', '105', '|', '106', '|', '107', '|', '108', '|', '109', '|', '110', '|', '111', '|', '112', '|', '113', '|', '114', '|', '115', '|', '116', '|', '117', '|', '118', '|', '119', '|', '120', '|', '121', '|', '122', '|', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '|', '*', '.', '#1', '.', '|', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '46', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '.', '?', '.', '69', '43', '45', '|', '?', '.', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '.', '?', '.', '#2', '.', '|', '43', '#3', '.', '|', '45', '#4', '.', '|', '42', '#5', '.', '|', '47', '#6', '.', '|', '40', '#7', '.', '|', '41', '#8', '.', '|', '35', '.'],
    [('return WHITESPACE', 'WHITESPACE'), ('return ID', 'ID'), ('return NUMBER', 'NUMBER'), ('return PLUS', 'PLUS'), ('return MINUS', 'MINUS'), ('return TIMES', 'TIMES'), ('return DIV', 'DIV'), ('return LPAREN', 'LPAREN'), ('return RPAREN', 'RPAREN')]
)

raw_file = input("Enter the path of the yal testing file: ")
test_file = replace_slash_with_backslash(raw_file)
file_name = os.path.basename(test_file).split('.')[0]
output_file = f"./out/{file_name}_tokens.txt"
output_type = "analysis"

def return_token(found_token):

    WHITESPACE = "WHITESPACE"
    ID = "ID"
    NUMBER = "NUMBER"
    PLUS = "PLUS"
    MINUS = "MINUS"
    TIMES = "TIMES"
    DIV = "DIV"
    LPAREN = "LPAREN"
    RPAREN = "RPAREN"

    if (found_token == WHITESPACE):
        return WHITESPACE
    if (found_token == ID):
        return ID
    if (found_token == NUMBER):
        return NUMBER
    if (found_token == PLUS):
        return PLUS
    if (found_token == MINUS):
        return MINUS
    if (found_token == TIMES):
        return TIMES
    if (found_token == DIV):
        return DIV
    if (found_token == LPAREN):
        return LPAREN
    if (found_token == RPAREN):
        return RPAREN

simulate_yalex_file(test_file, output_file, dfa, output_type, return_token)
