# This file was generated by the Yalex compiler.
# Do not modify this file.

import os
from algorithms.direct_construction import dfa_direct_construction
from yal_processing.simulate_yalex_file import simulate_yalex_file
from utils.path_cleaner import replace_slash_with_backslash

dfa = dfa_direct_construction(
    ['32', '9', '|', '10', '|', '+', '#0', '.', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '46', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '.', '?', '.', '69', '43', '45', '|', '?', '.', '48', '49', '|', '50', '|', '51', '|', '52', '|', '53', '|', '54', '|', '55', '|', '56', '|', '57', '|', '+', '.', '?', '.', '#1', '.', '|', '43', '#2', '.', '|', '42', '#3', '.', '|', '40', '#4', '.', '|', '41', '#5', '.', '|', '35', '.'],
    [('return WHITESPACE', 'WHITESPACE'), ('return NUMBER', 'NUMBER'), ('return PLUS', 'PLUS'), ('return TIMES', 'TIMES'), ('return LPAREN', 'LPAREN'), ('return RPAREN', 'RPAREN')]
)

raw_file = input("Enter the path of the yal testing file: ")
test_file = replace_slash_with_backslash(raw_file)
file_name = os.path.basename(test_file).split('.')[0]
output_file = f"./out/{file_name}_tokens.txt"
output_type = "analysis"

def return_token(found_token):

    WHITESPACE = "WHITESPACE"
    NUMBER = "NUMBER"
    PLUS = "PLUS"
    TIMES = "TIMES"
    LPAREN = "LPAREN"
    RPAREN = "RPAREN"

    if (found_token == WHITESPACE):
        return WHITESPACE
    if (found_token == NUMBER):
        return NUMBER
    if (found_token == PLUS):
        return PLUS
    if (found_token == TIMES):
        return TIMES
    if (found_token == LPAREN):
        return LPAREN
    if (found_token == RPAREN):
        return RPAREN

simulate_yalex_file(test_file, output_file, dfa, output_type, return_token)
